### PR TITLE
Export of Chat from the ChatView

### PR DESCRIPTION
**Pull request by philippzagar**
# Export of Chat

## :recycle: Current situation & Problem
As of now, SpeziChat doesn't provide any option to export the content of a `ChatView`.

## :gear: Release Notes 
- The `ChatView` now provides functionality to export the `Chat` content as PDF, JSON, or textual UTF-8 file via a Share Sheet (or Activity View).

## :books: Documentation
- Inline docs added, README and DocC Articles updated.

## :white_check_mark: Testing
Manually tested, as UI testing the Share Sheet is complex.

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
- [X] I agree to follow the [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by philippzagar** [comment]
Example export of the chat:

|PDF output| JSON output| Text Output
|:--:|:--:|:--:|
|PDF output|JSON output|Text Output|

**Comment by vishnuravi** [comment]
This is a really helpful feature - thanks @philippzagar!

**Review by PSchmiedmayer — APPROVED** [review]
@philippzagar this looks great, thank you for the changes and additions!

**Comment by philippzagar** [comment]
@PSchmiedmayer UI tests are written, feel free to merge the PR and tag another "0.1.2" release 🥳

**Comment by PSchmiedmayer** [comment]
Thank you @philippzagar for finishing up the PR and adding a UI test! I will merge the PR and will tag a release 👍

**Pull request merged**
